import {
  checkEnvironment,
  createDeployment,
  getConfig,
  getDeploymentBatch,
  getDeploymentBatches,
  getDevDeployments,
  getSprintTickets,
  getTicketDevelopment,
  getWorkflowTargets,
  recordWorkflowTargetUsage,
  refreshDeploymentBatch,
  saveConfig,
  searchTickets,
  testConnection,
} from "./handlers";

export const bfd = {
  checkEnvironment,
  createDeployment,
  getDeploymentBatch,
  getDeploymentBatches,
  getConfig,
  getDevDeployments,
  getSprintTickets,
  getTicketDevelopment,
  getWorkflowTargets,
  recordWorkflowTargetUsage,
  refreshDeploymentBatch,
  saveConfig,
  searchTickets,
  testConnection,
};
